git add    .gitignore
git add    1.php
git add    app/Http/Controllers/CurrencyController.php
git add    app/Http/Controllers/HomeController.php
git add     app/Http/Resources/CurrencyCollection.php
git add       app/Library/Services/AppContent.php
git add       app/Library/Services/HostelSupport.php
git add       app/Notifications/CurrencyRatesImportRun.php
git add       database/migrations/2022_02_19_154105_create_permission_tables.php
git add       database/migrations/2022_03_09_141820_create_media_table.php
git add       database/seeders/__UsersTableSeeder.php
git add    public/.htaccess
git add    resources/js/Pages/Currencies/CurrentRates.vue
git add    resources/js/Pages/Home/Home.vue
git add    resources/js/Pages/Home/TopCurrenciesBlock.vue
git add       resources/js/components/Sidebar.vue
git add       resources/js/dashboard.js
git add       resources/views/app.blade.php

